version: '3.8'

services:
  web:
    build: .
    container_name: edoc_web
    ports:
      - "8081:80"  # Map port 8080 on the host to port 80 in the container
    networks:
      - edoc_network

  db:
    image: mysql:5.7
    container_name: edoc_db
    restart: always
    environment:
      MYSQL_DATABASE: edoc
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
      - ./SQL_Database_edoc.sql:/docker-entrypoint-initdb.d/SQL_Database_edoc.sql
    networks:
      - edoc_network

networks:
  edoc_network:
    driver: bridge

volumes:
  db_data:

